Databseの設計
yoshiken/yeahcheese pull request #10
Opened 2018-04-10 04:06 UTC by yoshiken

サービス上で使用するデータベースを設計、CREAT文の作成を行いました。 (#9 のFlowchartをベースにしています。)

2018-04-10 16:18 UTC, sen-higa requested changes
以下気になった点です！

2018-04-10 16:18 UTC, sen-higa commented on working/DB_Design_document.md
> +## イベント担当情報[photo_charge]
こちらのテーブルって必要ですかね？？
event_infoにphotographer_id含めてしまえばいいんじゃないかなーと思いましたが、いかがでしょう。
何か意図があれば教えてください！

2018-04-10 16:18 UTC, sen-higa commented on working/DB_Design_document.md
> +  pevent_id SERIAL PRIMARY KEY NOT NULL ,
pevent_idはevent_idのことですかね…？

2018-04-10 16:25 UTC, sen-higa commented
あとFlowchart.xmlをベースにとのことでしたが、そのファイルの内容をどうやって確認したらいいのかわからなかったので、確認していません…

2018-04-10 23:53 UTC, yoshiken commented on working/DB_Design_document.md
> +  pevent_id SERIAL PRIMARY KEY NOT NULL ,
ご指摘の通りtypoしておりました :bow:

2018-04-11 00:09 UTC, yoshiken commented on working/DB_Design_document.md
> +## イベント担当情報[photo_charge]
イベントに対して担当者の変更を考えた際に、イベントUUIDに対して担当者のUUIDのみを紐付けた独立したテーブルを作成したほうが良い。という思考の元分割したのですが、今回の仕様上そういった機能は無いので不要でしたね…ご指摘通りevent_infoに統合します :bow:

2018-04-11 00:09 UTC, yoshiken commented on working/DB_Design_document.md
> +## イベント担当情報[photo_charge]
ご参考程度に教えていただきたいのですが、もしそういったそういった担当者の変更、担当者の兼任、1イベントに対して複数の担当者(写真アップロード者)などがあった場合は今回のように分割したほうがよいのでしょうか？

2018-04-11 00:13 UTC, yoshiken commented
Flowchart.xmlは[draw.io](https://www.draw.io/)でFlowchart図を記述するためのファイルでFlowchart.xml = Flowchart.jpgと捉えていただければと思います。
余計なレビューの手間を省くため今後のcommitから/working/Flowchart.xmlを外しておきます :bow:

2018-04-11 03:55 UTC, sen-higa commented on working/DB_Design_document.md
> +## イベント担当情報[photo_charge]
複数の担当者が存在し得る場合は分割してもよさそうですね！
もしくは、event_infoテーブルにownerとしてphotographer_idを保存、共同編集者として他のphotographer_idを保存ということもできるのかなーと思ったりしました。

2018-04-11 04:02 UTC, sen-higa approved these changes
確認しました！問題無いと思います。
図も確認できましたー。ありがとうございます！

2018-04-11 04:16 UTC, yoshiken commented on working/DB_Design_document.md
> +## イベント担当情報[photo_charge]
なるほど…ownerと共同編集者という概念が浮かんで無かったので勉強になりました :bow:

2018-04-11 04:16 UTC, yoshiken commented
こちらこそありがとうございます :bow:

2018-04-11 04:16 UTC, merged