ユーザー登録画面遷移の作成
yoshiken/yeahcheese pull request #11
Opened 2018-04-11 09:47 UTC by yoshiken

データベースからの認証機能はまだですが、ユーザー登録画面の遷移を作成しました。

2018-04-11 16:43 UTC, rymiyamoto requested changes
以下気になる点です
分からなかったら、メンションください

2018-04-11 16:43 UTC, rymiyamoto commented on app/action/Creat/Photographer.php
> +    public function prepare()
遷移させるだけならperformでいいかな
prepareはethanm的にバリデーションとかをするのが主な使い方かと

参考
https://github.com/ethnamphp/ethnam/blob/a23548ae70d43366ba0e1f88341172bc73e387ec/doc/14-login-do.md#バリデーションフォーム値の検証
> ようするに、prepare()メソッドでフォーム値の検証を行うこと、perform()メソッドでは全てのデータはサニタイズされているという前提で処理を行うことが出来る、安全且つ簡潔なコードが書けるというわけです(やっぱりStrutsの真似)。
>

2018-04-11 16:43 UTC, rymiyamoto commented on app/action/Creat/Photographer/Do.php
> +      'custom' => 'checkMailaddress',
細かいからスルーでもいいけど、ここだけインデントずれてる
好みもあるけど、連想配列とかで要素を羅列するとき、ずれてると読みにくいので

2018-04-11 16:43 UTC, rymiyamoto commented on www/js/creat/form.js
> +});
ファイルの末尾は空行入れておいてください

2018-04-11 16:43 UTC, rymiyamoto commented on www/js/creat/form.js
> +$('#form_creat_photographer').submit(function() {
このままだとjs動かないと思うよ
DOM構築が完了した後に実行するようにすると動くはず
```js
$(function () {
  // ざっくばらんな処理
});
```

2018-04-11 16:43 UTC, rymiyamoto commented on www/js/creat/form.js
> +  if ($("#password")[0].value == '' || $("#password_confirm")[0].value == '') {
入力されているかどうかはhtml5のrequired属性使えばjsで描く必要ないかなと
```html
<input type="password" name="password" value="" id="password" required>
```
http://www.htmq.com/html5/input_required.shtml

2018-04-11 16:43 UTC, rymiyamoto commented on www/js/creat/form.js
> +  }else if ($("#password")[0].value != $("#password_confirm")[0].value) {
`$('input[name="password"]').val()` みたいな感じで書いておくとidも指定せずに済むし、今みたいにindexが0の時を参照する必要なくなるかなと

2018-04-11 16:43 UTC, rymiyamoto commented on app/action/Creat/Photographer/Do.php
> +        } else {
jsでパスワードの妥当性は一応調べられてはいますが、悪意のあるユーザーが無理やりcurlしてきたとき対応できないのでパスワードが同一であるかはphpでも見ておくべきだと思います

2018-04-11 23:56 UTC, yoshiken commented on app/action/Creat/Photographer.php
> +    public function prepare()
@rymiyamoto 
ご指摘ありがとうございます。
以下の規約を見るとprepare()内で遷移・遷移条件、perform()内でDB処理などを書いているようにみえるのですが、Ethnamの公式ドキュメントに従った方が良いのでしょうか？

[PHPコーディング規約 - はいチーズ - Redmine](https://redmine.8122.jp/projects/hicheese/wiki/PHP%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84#Ethna%E4%B8%8A%E3%81%AE%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84)
[Ethna設計規約 - はいチーズ - Redmine](https://redmine.8122.jp/projects/hicheese/wiki/Ethna%E8%A8%AD%E8%A8%88%E8%A6%8F%E7%B4%84#%E3%82%A2%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%AF%E3%83%A9%E3%82%B9)

2018-04-12 00:08 UTC, rymiyamoto commented on app/action/Creat/Photographer.php
> +    public function prepare()
それは、Validationとか認証とかで別画面出す時の話かな
正規の画面に遷移させるなら perform でやるのがうちのサービスでも一般的

2018-04-12 00:27 UTC, yoshiken commented on app/action/Creat/Photographer.php
> +    public function prepare()
承知しました！ありがとうございます！

2018-04-12 01:20 UTC, FujimoriYuya commented on app/action/Creat/Photographer/Do.php
> +        $passowrd_compare = $this->af->get('password') == $this->af->get('password_confirm') ? true : false;
比較する際には型まで比較をするようにした方がいいと思います。
http://php.net/manual/ja/language.operators.comparison.php

2018-04-12 01:20 UTC, FujimoriYuya commented on app/action/Creat/Photographer/Do.php
> +        if ($this->af->validate() > 0 && $passowrd_compare) {
`$passowrd_compare` (微妙にタイプミス?) は 一箇所でしか使われていないので
変数に入れる必要はない気がします。

```
($this->af->validate() > 0 && $this->af->get('password') == $this->af->get('password_confirm'))
```

2018-04-12 04:51 UTC, FujimoriYuya commented on app/action/Creat/Photographer/Do.php
> +        'password' => [
今回passに文字数制限は必要ない感じでしょうか
(無しなら無しでもいいと思います)

2018-04-12 04:51 UTC, FujimoriYuya commented on app/action/Creat/Photographer/Do.php
> +      'mailaddress' => [
'mailaddress'だけインデントがずれているのが気になります。

2018-04-12 04:54 UTC, FujimoriYuya commented on app/action/Creat/Photographer/Do.php
> +    public $form = array(
`$form = array(***, ***)`
より
`$form = [***, ***]`
の方が短くていいと思います。

2018-04-12 09:48 UTC, rymiyamoto approved these changes
確認しました、問題ないと思います
マージしちゃって下さい

2018-04-12 23:53 UTC, yoshiken commented
レビューありがとうございます :bow:

2018-04-12 23:53 UTC, merged