新規登録処理機能no追加
yoshiken/yeahcheese pull request #13
Opened 2018-04-13 05:08 UTC by yoshiken

2018-04-13 06:27 UTC, rymiyamoto reviewed
以下気になる点です

2018-04-13 06:27 UTC, rymiyamoto commented on app/Yeahcheese_UserManager.php
> +    public function comparisonPassword($password, $password_confirm)
docと型宣言忘れないでね（以下同様）
docに関してはpsr-2的にも引っかかるし、型宣言はやっておくと予期せぬバグに気付けるので

psr-2に関連する記事載せといたので、どっちかは簡単に目を通しておいてね
- [ゆるいやつ](https://www.slideshare.net/wterada/psr1-psr2-5)
- [詳しいやつ](http://www.infiniteloop.co.jp/docs/psr/psr-2-coding-style-guide.html)

2018-04-13 06:27 UTC, rymiyamoto commented on app/Yeahcheese_UserManager.php
> +        $dbresult = $db->query("SELECT * FROM photographer_info WHERE photographer_mailaddress = $1", $mailaddress);
$db->getRow() というものがあって、こいつを使うと最初に一致した1レコード分を取得できるので、いちいち `fetchRow()` せずに済むよ
```php
$sql = "
    SELECT *
      FROM photographer_info
     WHERE photographer_mailaddress = ? 
";
if ($this->db->getRow($sql, $mailaddress)) {
    return Ethna::raiseNotice('このメールアドレスは既に登録されています', E_MAILADDRESS_REGISTERED);
}
return null;
```

ちなみに取りたい要素によってこんな感じで使い分けができる

|全件|1レコード|特定のカラムのみ|
|:---:|:---:|:---:|
|[getAll()](http://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:getall)|[getRow()](http://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:getone&s[]=getone)|[getOne()](http://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:getone&s[]=getone)|

2018-04-13 06:27 UTC, rymiyamoto commented on app/action/Creat/Photographer/Do.php
> +        if ($this->af->validate()>0) {
おそらくミスだと思いますが、 比較演算子の前後はスペースのほうが読みやすいです
[公式](http://php.net/manual/ja/language.operators.comparison.php)もそうなってますし

2018-04-13 06:27 UTC, rymiyamoto commented on app/Yeahcheese_UserManager.php
> +    public function isRegisteredMailaddress($mailaddress, $db)
実はいちいち `$db` 渡さなくても AppManager を継承してたらそのまま使えるよ
https://github.com/ethnamphp/ethnam/blob/master/doc/db.md#appmanager内でのdbオブジェクトの使用方法

2018-04-16 01:35 UTC, sen-higa requested changes
以下気になった点です！

2018-04-16 01:35 UTC, sen-higa commented on app/Yeahcheese_UserManager.php
> +    public function comparisonPassword(string $password, string $password_confirm)
戻り値の型宣言も付けてあげましょう。`isRegisteredMailaddress`も同様です。

`public function comparisonPassword(string $password, string $password_confirm): ?\Ethna_Error`

2018-04-16 01:35 UTC, sen-higa commented on app/Yeahcheese_UserManager.php
> +        $db = $this->backend->getDB();
これも不要じゃないですかね？
すぐ`$this->db->getRow()`が操作可能ではないかと思ったのですが、ダメでした？？

2018-04-16 01:54 UTC, yoshiken commented on app/Yeahcheese_UserManager.php
> +    public function comparisonPassword(string $password, string $password_confirm)
@sen-higa 
phpの返り値型宣言は `関数 hoge(x) :(型名) `とはわかったのですが、
http://php.net/manual/ja/functions.returning-values.php

`public function comparisonPassword(string $password, string $password_confirm): ?\Ethna_Error`
の`?\Ethna_Error`部分の意味がいまいち理解できてません。`Ethana_Error`はそういうメソッドなんだなとはなんとなくわかるのですが `?\`の部分が調べてもでてこないのでご教授いただければと思います :bow:

2018-04-16 03:25 UTC, sen-higa commented on app/Yeahcheese_UserManager.php
> +    public function comparisonPassword(string $password, string $password_confirm)
私も同じこと思いました！(w
まず、`?`を使うとnullを許容してくれるそうです。
http://php.net/manual/ja/migration71.new-features.php

次にバックスラッシュですが、これは完全修飾名というものかと思われます。
http://php.net/manual/ja/language.namespaces.faq.php#language.namespaces.faq.full

完全修飾名についてがつまりどういう時に使われるのかがイマイチ理解できなかったので、わかったらぜひ教えてください…m(_ _)m

2018-04-16 07:13 UTC, yoshiken commented on app/Yeahcheese_UserManager.php
> +    public function comparisonPassword(string $password, string $password_confirm)
@sen-higa 色々調べてみたんですが、

1 .PHPは5.3未満の場合名前空間が存在せず、常にグローバルな名前の呼び出しのみを行っていた
2. PHP5.3移行に名前空間すなわち、スラッシュで区切ることによって冗長なクラス名を防ぐことが可能になった
3. 仕様として完全修飾名の場合グローバル(ルート)から、つまりは呼ばれたaction/hoge.phpから継承を遡りたどり着いた先から階層を重ねていく。
4. 完全装飾をつけない場合、まず現在のクラスの名前の一段階上にその名前をつけて関数あるいは定数がない場合はグローバル、つまりは3で記した完全修飾名を呼びだす。

らしいです

このapp/Yeahcheese_UserManager.phpに限って言うと

Yeahcheese_UserManager ← 継承 ←  [Ethna_AppManager](https://github.com/ethnamphp/ethnam/blob/a23548ae70d43366ba0e1f88341172bc73e387ec/src/AppManager.php) 内のEthna_AppManagerクラスでEthna::isErrorを呼び出し ← [Ethna.php](https://github.com/ethnamphp/ethnam/blob/a23548ae70d43366ba0e1f88341172bc73e387ec/src/Ethna.php)がルートとなってそのなかでEthna_Errorオブジェクトが生成されており、ルート上で生成されたので`/Ethna_Error`で呼び出すことが可能となっています。

もし完全修飾名をつなかった場合は最初に`Ethna_Error/Yeahcheese_UserManager.php` = Yeahcheese_UserManager.phpの継承元にEthna_Errorクラスがいないか探し、いなかった場合はルートのEthna.phpを探す感じになります。

今回の場合は直接Ethna_AppManager読んでいるので問題はないのですが、非完全修飾名で多重継承時、途中(一つ上の継承)に同一クラス名や関数があった場合はそちらが上書きされる恐れがあるので完全修飾名を指定したほうが安全そうですね。

e.g)フォルダー階層ではなく継承での階層と見てください
example
|--hoge
|--fuga
  |-piyo
  |--hoge
  |   |--bar
  |--foo

| |完全修飾名(/example/hoge)|非完全修飾名(hoge)|
|:-:|:-:|:-:|
|/example/fuga/hoge/bar|/example/hoge/|/example/fuga/hoge/|
|上記以外|/example/hoge|/example/hoge|

ちなみにEthna_Errorクラスの引数は↓の通りとなっています
($message, $code, ETHNA_ERROR_DUMMY, E_USER_ERROR, $userinfo, 'Ethna_Error');

2018-04-16 07:26 UTC, yoshiken commented on app/Yeahcheese_UserManager.php
> +        $db = $this->backend->getDB();
class Ethna_AppManagerみたらすでに$dbオブジェクト生成されてました :bow:

2018-04-16 10:29 UTC, sen-higa approved these changes
戻り値の型宣言の微修正以外問題無いと思います！
完全修飾名について、丁寧に調べていただき、ありがとうございます！
(そして時間取らせてしまってごめんなさい…:bow:)

2018-04-16 10:29 UTC, sen-higa commented on app/Yeahcheese_UserManager.php
> +    public function comparisonPassword(string $password, string $password_confirm):?\Ethna_Error
コロンの後ろに1スペースお願いします！

2018-04-16 10:29 UTC, sen-higa commented on app/Yeahcheese_UserManager.php
> +    public function comparisonPassword(string $password, string $password_confirm):?\Ethna_Error
こちら直すだけでしたら、再レビューは不要ですー

2018-04-17 02:39 UTC, yoshiken commented
レビューありがとうございます :bow:

2018-04-17 02:39 UTC, merged